### ISSUE TITLE
长对话，返回很多数据的时候，返回一半就没有数据了，是不是代理服务有timeout或者大小限制

### ISSUE THREAD

**Issue by mengyou658** [xyhelper/xyhelper-desktop#1]
你好，如题
![image](https://user-images.githubusercontent.com/1542297/229342696-dbc8d582-e0e1-4824-9606-fddd10b4ab08.png)

**Comment by gcslaoli** [comment]
在对话里 发送继续 就会继续生成了

**Comment by gcslaoli** [comment]
说 继续

**Comment by gcslaoli** [comment]
服务端倒没timeout限制 官方回复也是这样的 过长的会被切割 要说继续

**Comment by mengyou658** [comment]
好的，收到，谢谢
